# Assignment 1

### 5 functions

- torch.is_tensor(obj)
- torch.as_tensor(data, dtype=None, device=None)
- torch.clamp(input, min, max, out=None)
- torch.fill(value)
- torch.max(input, other, out=None)

In [18]:
# Import torch and other required modules
import torch

## Function 1 - torch.is_tensor(obj)

Checks if the obj provided is a tensor where torch.Tensor is a multi-dimensional matrix containing elements of a single data type. 

In [19]:
# Example 1 - working
x = torch.tensor([[1.1, 2], [3, 4.]])
torch.is_tensor(x)

True

When x is defined as torch.tensor() it returns True

In [15]:
# Example 2 - working
y = [['hi', 'YY'], ['bye', 'JJ']]
torch.is_tensor(y)

False

When y is defined as multi dimensional array with single data type, it is still not considered tensor

In [13]:
# Example 3 - breaking (to illustrate when it breaks)
torch.is_tensor()

NameError: name 'z' is not defined

It will only break when the object is not provided or even if it is provided, it is not defined

Use this function to check if the object is tensor - multi-dimensional matrix containing elements of a single data type

## Function 2 - torch.as_tensor(data, dtype=None, device=None)

This function converts the data into a torch.Tensor

In [60]:
# Example 1 - before
x = [7,0,5,4]
print(torch.is_tensor(x))
newX = torch.as_tensor(x, dtype=torch.double)
print(torch.is_tensor(newX))
newX

False
True


tensor([7., 0., 5., 4.], dtype=torch.float64)

It can convert arrays into torch.tensor - even the single dimensional array

In [44]:
# Example 2 - working
z = torch.tensor([7,0,5,4])
torch.as_tensor(z, dtype=torch.bool)

tensor([ True, False,  True,  True])

Type of array or tensor can be changed from int to boolean and change it to tensor

In [43]:
# Example 3 - breaking (to illustrate when it breaks)
y = [['hi', 'YY'], ['bye', 'JJ']]
torch.as_tensor(y)

ValueError: too many dimensions 'str'

It cannot change array with string into tensor

Use this to change normal arrays into tensor

## Function 3 - torch.clamp(input, min, max, out=None)

It accepts tensor as input and whichever values that falls below min will be set as min and values above max will be set as max

In [64]:
# Example 1 - working
a = torch.randint(low=0, high=100, size=(3,5))
print(a)
torch.clamp(a, 10, 60)

tensor([[98, 65, 16,  8, 90],
        [11, 24, 21, 17, 19],
        [91, 78, 49, 50, 49]])


tensor([[60, 60, 16, 10, 60],
        [11, 24, 21, 17, 19],
        [60, 60, 49, 50, 49]])

set min and max for int

In [69]:
# Example 2 - working
b = torch.rand(4)
print(b)
torch.clamp(b, 0.3, 0.7)

tensor([0.8445, 0.4465, 0.2089, 0.2704])


tensor([0.7000, 0.4465, 0.3000, 0.3000])

Set min and max for double 

In [79]:
# Example 3 - breaking (to illustrate when it breaks)
c = torch.tensor([True, False])
print(c)
torch.clamp(c, 0.3, 0.7)

tensor([ True, False])


RuntimeError: "clamp_cpu" not implemented for 'Bool'

It can only be applied to real numbers

Use this function to set minimum and maximum

## Function 4 - torch.fill(value)

Used to fill a tensor with a certain value.

In [93]:
# Example 1 - working
a = torch.randint(low=0, high=100, size=(5,5))
a.fill_(False)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

Fills an existing tensor with a value

In [88]:
# Example 2 - working
b = torch.randint(low=0, high=100, size=(5,5))
b.fill_(3.33333)

tensor([[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]])

Since the data type for the tensor is int, when attempted to fill 3.3333, it has been changed to int

In [96]:
# Example 3 - breaking (to illustrate when it breaks)
c = [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]]
c.fill_(0)

AttributeError: 'list' object has no attribute 'fill_'

This only works when the target is tensor

Use this function to fill tensor with a value or to convert

## Function 5 - torch.max(input, other, out=None)

Gives the max within a tensor or gives the max tensor as a result of 2 tensors

In [100]:
# Example 1 - working
a = torch.randint(low=0, high=100, size=(5,5))
print(a)
b = torch.randint(low=0, high=100, size=(5,5))
print(b)
torch.max(a,b)

tensor([[86, 35, 54, 30, 20],
        [ 7, 22,  0, 92, 50],
        [33, 19, 87, 12, 73],
        [37, 46, 78, 33, 24],
        [60, 14, 83, 61, 78]])
tensor([[54, 40, 14, 34, 18],
        [ 5, 93, 55, 67, 62],
        [14, 96, 30, 89, 69],
        [88, 29, 88, 25, 76],
        [47,  6, 57, 17, 76]])


tensor([[86, 40, 54, 34, 20],
        [ 7, 93, 55, 92, 62],
        [33, 96, 87, 89, 73],
        [88, 46, 88, 33, 76],
        [60, 14, 83, 61, 78]])

When tensor a and b is given, it will take the max values of the tensor to combine into 1

In [101]:
# Example 2 - working
a = torch.randint(low=0, high=100, size=(5,5))
print(a)
torch.max(a)

tensor([[57, 92, 83, 45, 65],
        [36,  6,  0, 83, 30],
        [27, 83, 63, 49, 19],
        [73, 70, 42, 79, 56],
        [86, 36, 58, 80, 22]])


tensor(92)

When only 1 tensor is given, it returns the highest value inside the tensor

In [98]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.randint(low=0, high=100, size=(5,5))
print(a)
b = torch.randint(low=0, high=100, size=(3,5))
print(b)
torch.max(a, b)

tensor([[47, 11, 84, 21, 81],
        [97,  8, 37, 32, 89],
        [61, 21, 29,  1, 58],
        [38, 65,  4, 57, 39],
        [71, 81, 53, 95, 38]])
tensor([[14, 74, 55, 14, 69],
        [99,  3, 43, 94, 69],
        [37, 82, 95, 34, 47]])


RuntimeError: The size of tensor a (5) must match the size of tensor b (3) at non-singleton dimension 0

It will not work when the 2 tensors are not the same size

Use this to compare 2 functions and to get the maximum

## Reference Links
All of these can be found in the documentation
* Official documentation: https://pytorch.org/docs/stable/index.html

In [102]:
!pip install jovian --upgrade --quiet

In [103]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
